#!/usr/bin/python
import basNetPredict as net
import sys
# get edgelist
edgelist,nodes = net.file2edgelist(sys.argv) 
# get graph
G = net.edgelist2graph(edgelist)
# get scc and wcc
buffer = net.getSubGraphNerighbourOverlap(G)

# number
number = int(sys.argv[2])

bestmatches = net.getNBestMatch(buffer, number)

net.prints(bestmatches)
# print prediction
